from setuptools import setup

setup(
    name='MkDepends',
    version='',
    packages=['venv1.Lib.distutils', 'venv1.Lib.encodings', 'venv1.Lib.importlib', 'venv1.Lib.collections',
              'venv1.Lib.site-packages.pip', 'venv1.Lib.site-packages.pip.req', 'venv1.Lib.site-packages.pip.vcs',
              'venv1.Lib.site-packages.pip.utils', 'venv1.Lib.site-packages.pip.compat',
              'venv1.Lib.site-packages.pip.models', 'venv1.Lib.site-packages.pip._vendor',
              'venv1.Lib.site-packages.pip._vendor.distlib', 'venv1.Lib.site-packages.pip._vendor.distlib._backport',
              'venv1.Lib.site-packages.pip._vendor.colorama', 'venv1.Lib.site-packages.pip._vendor.html5lib',
              'venv1.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv1.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv1.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv1.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv1.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'venv1.Lib.site-packages.pip._vendor.lockfile', 'venv1.Lib.site-packages.pip._vendor.progress',
              'venv1.Lib.site-packages.pip._vendor.requests', 'venv1.Lib.site-packages.pip._vendor.requests.packages',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv1.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv1.Lib.site-packages.pip._vendor.packaging', 'venv1.Lib.site-packages.pip._vendor.cachecontrol',
              'venv1.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv1.Lib.site-packages.pip._vendor.webencodings', 'venv1.Lib.site-packages.pip._vendor.pkg_resources',
              'venv1.Lib.site-packages.pip.commands', 'venv1.Lib.site-packages.pip.operations',
              'venv1.Lib.site-packages.wheel', 'venv1.Lib.site-packages.wheel.tool',
              'venv1.Lib.site-packages.wheel.signatures', 'venv1.Lib.site-packages.setuptools',
              'venv1.Lib.site-packages.setuptools.extern', 'venv1.Lib.site-packages.setuptools.command',
              'venv1.Lib.site-packages.pkg_resources', 'venv1.Lib.site-packages.pkg_resources.extern',
              'venv1.Lib.site-packages.pkg_resources._vendor',
              'venv1.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='David Sackstein',
    author_email='',
    description=''
)
